%General Mission Analysis Tool(GMAT) Script
%Created: 2026-04-11 16:16:50


%----------------------------------------
%---------- Spacecraft
%----------------------------------------
Create Spacecraft Sat1;
Sat1.DateFormat = UTCGregorian;
Sat1.Epoch = '15 Apr 2026 17:05:00.000';
Sat1.CoordinateSystem = EarthMJ2000Eq;
Sat1.DisplayStateType = Keplerian;
Sat1.SMA = 7178.136299999999;  % Altura aprox 800 km
Sat1.ECC = 0.0009999999999998818;
Sat1.INC = 98.59999999999999;       % Orbita heliosincronica
Sat1.RAAN = 13;
Sat1.AOP = 0;
Sat1.TA = 359.9999991462263;
Sat1.DryMass = 3;      % Masa: 3 kg (Nanosatelite 3U) [cite: 20]
Sat1.Cd = 2.2;
Sat1.Cr = 1.8;
Sat1.DragArea = 0.03;
Sat1.SRPArea = 0.03;
Sat1.SPADDragScaleFactor = 1;
Sat1.SPADSRPScaleFactor = 1;
Sat1.AtmosDensityScaleFactor = 1;
Sat1.ExtendedMassPropertiesModel = 'None';
Sat1.NAIFId = -10005001;
Sat1.NAIFIdReferenceFrame = -9005001;
Sat1.OrbitColor = Red;
Sat1.TargetColor = Teal;
Sat1.OrbitErrorCovariance = [ 1e+70 0 0 0 0 0 ; 0 1e+70 0 0 0 0 ; 0 0 1e+70 0 0 0 ; 0 0 0 1e+70 0 0 ; 0 0 0 0 1e+70 0 ; 0 0 0 0 0 1e+70 ];
Sat1.CdSigma = 1e+70;
Sat1.CrSigma = 1e+70;
Sat1.Id = 'SatId';
Sat1.Attitude = CoordinateSystemFixed;
Sat1.SPADSRPInterpolationMethod = Bilinear;
Sat1.SPADSRPScaleFactorSigma = 1e+70;
Sat1.SPADDragInterpolationMethod = Bilinear;
Sat1.SPADDragScaleFactorSigma = 1e+70;
Sat1.AtmosDensityScaleFactorSigma = 1e+70;
Sat1.ModelFile = 'aura.3ds';
Sat1.ModelOffsetX = 0;
Sat1.ModelOffsetY = 0;
Sat1.ModelOffsetZ = 0;
Sat1.ModelRotationX = 0;
Sat1.ModelRotationY = 0;
Sat1.ModelRotationZ = 0;
Sat1.ModelScale = 1;
Sat1.AttitudeDisplayStateType = 'Quaternion';
Sat1.AttitudeRateDisplayStateType = 'AngularVelocity';
Sat1.AttitudeCoordinateSystem = EarthMJ2000Eq;
Sat1.EulerAngleSequence = '321';

%----------------------------------------
%---------- Ground Station (UNDAV)
%----------------------------------------
Create GroundStation UNDAV_Station;
UNDAV_Station.OrbitColor = Thistle;
UNDAV_Station.TargetColor = DarkGray;
UNDAV_Station.CentralBody = Earth;
UNDAV_Station.StateType = Spherical;
UNDAV_Station.HorizonReference = Sphere;
UNDAV_Station.Location1 = -34.66;  % Latitud
UNDAV_Station.Location2 = 301.61; % Longitud Este (360 - 58.39)
UNDAV_Station.Location3 = 0.01;   % Altitud en km
UNDAV_Station.Id = 'StationId';
UNDAV_Station.IonosphereModel = 'None';
UNDAV_Station.TroposphereModel = 'None';
UNDAV_Station.DataSource = 'Constant';
UNDAV_Station.Temperature = 295.1;
UNDAV_Station.Pressure = 1013.5;
UNDAV_Station.Humidity = 55;
UNDAV_Station.MinimumElevationAngle = 7;


%----------------------------------------
%---------- ForceModels and Propagators
%----------------------------------------
Create ForceModel EarthPointProp_ForceModel;
EarthPointProp_ForceModel.CentralBody = Earth;
EarthPointProp_ForceModel.PrimaryBodies = {Earth};
EarthPointProp_ForceModel.Drag = None;
EarthPointProp_ForceModel.SRP = Off;
EarthPointProp_ForceModel.RelativisticCorrection = Off;
EarthPointProp_ForceModel.ErrorControl = RSSStep;
EarthPointProp_ForceModel.GravityField.Earth.Degree = 4;
EarthPointProp_ForceModel.GravityField.Earth.Order = 4;
EarthPointProp_ForceModel.GravityField.Earth.StmLimit = 100;
EarthPointProp_ForceModel.GravityField.Earth.PotentialFile = 'JGM2.cof';
EarthPointProp_ForceModel.GravityField.Earth.TideModel = 'None';

%----------------------------------------
%---------- Propagators
%----------------------------------------

Create Propagator EarthPointProp;
EarthPointProp.FM = EarthPointProp_ForceModel;
EarthPointProp.Type = RungeKutta89;
EarthPointProp.InitialStepSize = 60;
EarthPointProp.Accuracy = 9.999999999999999e-12;
EarthPointProp.MinStep = 0.001;
EarthPointProp.MaxStep = 2700;
EarthPointProp.MaxStepAttempts = 50;
EarthPointProp.StopIfAccuracyIsViolated = true;

%----------------------------------------
%---------- Eclipse Locator
%----------------------------------------
Create EclipseLocator EclipseSat1;
EclipseSat1.Spacecraft = Sat1;
EclipseSat1.Filename = 'Eclipses_Nanosat.txt';
EclipseSat1.OccultingBodies = {Earth};
EclipseSat1.InputEpochFormat = 'TAIModJulian';
EclipseSat1.InitialEpoch = '21545';
EclipseSat1.StepSize = 10;
EclipseSat1.FinalEpoch = '21545.138';
EclipseSat1.UseLightTimeDelay = true;
EclipseSat1.UseStellarAberration = true;
EclipseSat1.WriteReport = true;
EclipseSat1.RunMode = Automatic;
EclipseSat1.UseEntireInterval = true;
EclipseSat1.EclipseTypes = {'Umbra', 'Penumbra'};

%----------------------------------------
%---------- Contact Locator
%----------------------------------------
Create ContactLocator ContactoUNDAV;
ContactoUNDAV.Target = Sat1;
ContactoUNDAV.Filename = 'Contactos_UNDAV.txt';
ContactoUNDAV.InputEpochFormat = 'TAIModJulian';
ContactoUNDAV.InitialEpoch = '21545';
ContactoUNDAV.StepSize = 10;
ContactoUNDAV.FinalEpoch = '21545.138';
ContactoUNDAV.UseLightTimeDelay = true;
ContactoUNDAV.UseStellarAberration = true;
ContactoUNDAV.WriteReport = true;
ContactoUNDAV.RunMode = Automatic;
ContactoUNDAV.UseEntireInterval = true;
ContactoUNDAV.Observers = {UNDAV_Station};
ContactoUNDAV.LightTimeDirection = Transmit;
ContactoUNDAV.LeftJustified = false;
ContactoUNDAV.ReportPrecision = 6;
ContactoUNDAV.ReportFormat = 'Legacy';
ContactoUNDAV.IntervalStepSize = 0;
ContactoUNDAV.ReportTimeFormat = 'UTCGregorian';

%----------------------------------------
%---------- Subscribers (Reporte de Datos)
%----------------------------------------
% Archivo de salida para la Fase 2 [cite: 122]
Create ReportFile TelemetriaSat1;
TelemetriaSat1.SolverIterations = Current;
TelemetriaSat1.UpperLeft = [ 0 0 ];
TelemetriaSat1.Size = [ 0 0 ];
TelemetriaSat1.RelativeZOrder = 0;
TelemetriaSat1.Maximized = false;
TelemetriaSat1.Filename = 'Telemetria_Nanosat.csv';
TelemetriaSat1.Precision = 16;
TelemetriaSat1.Add = {Sat1.UTCGregorian, Sat1.Earth.Latitude, Sat1.Earth.Longitude, Sat1.Earth.Altitude};
TelemetriaSat1.WriteHeaders = true;
TelemetriaSat1.LeftJustify = On;
TelemetriaSat1.ZeroFill = Off;
TelemetriaSat1.FixedWidth = true;
TelemetriaSat1.Delimiter = ' ';
TelemetriaSat1.ColumnWidth = 23;
TelemetriaSat1.WriteReport = true;
TelemetriaSat1.AppendToExistingFile = false;

Create OpenFramesInterface DefaultOrbitView;
DefaultOrbitView.SolverIterations = Current;
DefaultOrbitView.UpperLeft = [ 0 0 ];
DefaultOrbitView.Size = [ 0 0 ];
DefaultOrbitView.RelativeZOrder = 0;
DefaultOrbitView.Maximized = false;
DefaultOrbitView.Add = {Sat1, Earth};
DefaultOrbitView.CoordinateSystem = EarthMJ2000Eq;
DefaultOrbitView.DrawObject = [ true true ];
DefaultOrbitView.DrawTrajectory = [ true true ];
DefaultOrbitView.DrawAxes = [ false false ];
DefaultOrbitView.DrawXYPlane = [ false false ];
DefaultOrbitView.DrawLabel = [ true true ];
DefaultOrbitView.DrawUsePropLabel = [ false false ];
DefaultOrbitView.DrawCenterPoint = [ true true ];
DefaultOrbitView.DrawEndPoints = [ true true ];
DefaultOrbitView.DrawVelocity = [ false false ];
DefaultOrbitView.DrawGrid = [ false false ];
DefaultOrbitView.DrawLineWidth = [ 2 2 ];
DefaultOrbitView.DrawMarkerSize = [ 10 10 ];
DefaultOrbitView.DrawFontSize = [ 20 20 ];
DefaultOrbitView.Axes = On;
DefaultOrbitView.AxesLength = 12756.2726;
DefaultOrbitView.AxesLabels = On;
DefaultOrbitView.FrameLabel = Off;
DefaultOrbitView.XYPlane = On;
DefaultOrbitView.EclipticPlane = Off;
DefaultOrbitView.EnableStars = On;
DefaultOrbitView.StarCatalog = 'inp_StarsHYGv3.txt';
DefaultOrbitView.StarCount = 40000;
DefaultOrbitView.MinStarMag = -2;
DefaultOrbitView.MaxStarMag = 6;
DefaultOrbitView.MinStarPixels = 1;
DefaultOrbitView.MaxStarPixels = 10;
DefaultOrbitView.MinStarDimRatio = 0.5;
DefaultOrbitView.ShowPlot = true;
DefaultOrbitView.ShowToolbar = true;
DefaultOrbitView.SolverIterLastN = 0;
DefaultOrbitView.ShowVR = false;
DefaultOrbitView.PlaybackTimeScale = 3600;
DefaultOrbitView.MultisampleAntiAliasing = On;
DefaultOrbitView.MSAASamples = 2;
DefaultOrbitView.DrawFontPosition = {'Top-Right', 'Top-Right'};

%----------------------------------------
%---------- Mission Sequence
%----------------------------------------
BeginMissionSequence;
% Simulamos 24 horas (86400 segundos) [cite: 88]
Propagate EarthPointProp(Sat1) {Sat1.ElapsedSecs = 86400.0};
