%----------------------------------------
%---------- Test ShadowState
%----------------------------------------
Create Spacecraft Sat1;
Sat1.DateFormat = UTCGregorian;
Sat1.Epoch = '22 Apr 2026 14:30:00.000';
Sat1.CoordinateSystem = EarthMJ2000Eq;
Sat1.DisplayStateType = Keplerian;
Sat1.SMA = 6978.136;
Sat1.ECC = 0.001;
Sat1.INC = 98.6;
Sat1.RAAN = 13;
Sat1.AOP = 0;
Sat1.TA = 0;
Sat1.DryMass = 3;
Sat1.Cd = 2.2;
Sat1.Cr = 1.8;
Sat1.DragArea = 0.03;
Sat1.SRPArea = 0.03;

Create Variable ShadowVal;

Create ForceModel FM;
FM.CentralBody = Earth;
FM.PrimaryBodies = {Earth};
FM.Drag = None;
FM.SRP = On;

Create Propagator Prop;
Prop.FM = FM;
Prop.Type = RungeKutta89;

Create ReportFile TestReport;
TestReport.Filename = 'Test_SunXYZ.csv';
TestReport.Add = {Sat1.UTCGregorian, Sat1.X, Sat1.Y, Sat1.Z, Sun.X, Sun.Y, Sun.Z};
TestReport.WriteHeaders = true;
TestReport.Delimiter = ' ';
TestReport.ColumnWidth = 23;

BeginMissionSequence;

Propagate Prop(Sat1) {Sat1.ElapsedSecs = 7200.0};
